---
## icli (for icinga1 made to 2) or use icingacli

- name: symlink icinga2 to icinga1
  file: src={{ item.src }} dest={{ item.dst }} state=link
  with_items:
    - { src: /var/lib/icinga2, dst: /var/lib/icinga }
    - { src: /var/cache/icinga2, dst: /var/cache/icinga }
    - { src: /var/run/icinga2/cmd/icinga2.cmd, dst: /var/lib/icinga/rw/icinga.cmd }

- file: dest=/var/lib/icinga2/rw mode=0755 owner=nagios
- file: dest=/var/lib/icinga2 mode=0755 owner=nagios

- template: src=statusdata.conf dest=/etc/icinga2/features-enabled/statusdata.conf mode=0644

- service: name=icinga2 state=restarted

