---

## to avoid dns issue (used in both client and server mode)
- name: get icinga2 server ip address
  shell: "ifconfig {{ icinga2_if }} | awk -F'[ :]' '/inet addr/ {print $13}'"
  changed_when: False
  register: ipaddr

- name: Include version-specific variables for Ubuntu.
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_version }}.yml"
  when: ansible_distribution == 'Ubuntu'
#- name: Include version-specific variables for RedHat
#  include_vars: "CentOS-{{ ansible_distribution_version.split('.')[0] }}.yml"
#  when: ansible_os_family == "RedHat" or ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- include: server.yml
  when: icinga2mode == 'server'

- include: client.yml
  when: icinga2mode == 'client'

